name: Trigger auto deployment for test01

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test01-AutoDeployTrigger-1874e539-92cf-445a-a728-9aa51182503a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TEST01_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TEST01_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEST01_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: cicdaz400.azurecr.io
          registryUsername: ${{ secrets.TEST01_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TEST01_REGISTRY_PASSWORD }}
          containerAppName: test01
          resourceGroup: az400projects
          imageToBuild: cicdaz400.azurecr.io/test01:${{ github.sha }}
          dockerfilePath: Dockerfile


